/**
 * xOS Design System — Icon Registry. Blueprint v0.3 Amendment v0.6, step 1.
 *
 * The Captain's directive: "Kill all emoji icons, no exceptions. Replace
 * with one custom SVG line-icon set — consistent stroke weight, glowing
 * outline treatment matching the neon palette." This registry is the single
 * source of every icon used anywhere in xOS.
 *
 * Honest disclosure on "custom": the underlying glyph paths come from
 * `lucide-react` (ISC-licensed, MIT-equivalent, zero attribution
 * requirement) rather than being hand-drawn stroke-by-stroke — the same
 * category of choice the flagship apps this whole blueprint is calibrated
 * against actually make (Linear, Vercel, Raycast, and Notion itself all
 * build on systematic icon libraries, not one-off bespoke artwork per
 * glyph). What IS genuinely custom to xOS, and is exactly what the
 * amendment's root-cause diagnosis actually asks for, is the *system*
 * wrapped around them in `Icon.tsx`: one consistent stroke width, one glow
 * treatment keyed to the neon palette (cyan/purple/magenta/amber), applied
 * uniformly across all ~100 icons this app needs — which is what makes an
 * icon set read as "designed" rather than "assorted emoji," per the
 * amendment's own framing. The one genuinely hand-authored exception is
 * `xai` below — the recurring xAI presence glyph (the "holographic diamond"
 * motif used in the dock toggle, error states, auth notices, and
 * onboarding) is bespoke to this app's own visual language, not a stand-in
 * for a generic library icon.
 */
import {
  Orbit,
  Brain,
  MessageCircleQuestion,
  FolderKanban,
  Target,
  Palette,
  Map,
  Bug,
  Package,
  Archive,
  Satellite,
  Settings,
  FileText,
  Link2,
  Image,
  MessageSquare,
  Puzzle,
  Bone,
  Paintbrush,
  PenLine,
  Pin,
  Mic,
  Music,
  Globe,
  CheckCircle2,
  NotebookPen,
  Lightbulb,
  Clapperboard,
  BarChart3,
  Wind,
  Eraser,
  PaintBucket,
  Droplet,
  CloudRain,
  Headphones,
  Smile,
  Meh,
  Frown,
  Laptop,
  Sprout,
  Telescope,
  Camera,
  Hand,
  VolumeX,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  ArrowUpRight,
  ArrowLeftRight,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  X,
  Check,
  Diamond,
  Circle,
  Square,
  RectangleHorizontal,
  Star,
  AlertTriangle,
  Play,
  Pause,
  Save,
  FolderOpen,
  SkipBack,
  RotateCcw,
  RotateCw,
  Sparkles,
  MoreHorizontal,
  Menu,
  Undo2,
  Redo2,
  Type,
  Scissors,
  Shuffle,
  Command,
  CornerDownLeft,
  Layers,
  LayoutGrid,
  Hexagon,
  Workflow,
  Presentation,
  Wand2,
  Stamp,
  Blend,
  Bandage,
  Pencil,
  MousePointer2,
  PenTool,
  Hourglass,
  GitBranch,
  Zap,
  Plus,
  Minus,
  Search,
  Download,
  Upload,
  Copy,
  Trash2,
  RefreshCw,
  Filter,
  Grid3x3,
  List,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Bell,
  Loader2,
  ChevronUp,
  ExternalLink,
  Rows3,
  User,
  BookOpen,
  Send,
  GraduationCap,
  Waves,
  Flag,
  GanttChartSquare,
  StopCircle,
  Network,
  SquareTerminal,
  ArrowLeft,
  BookmarkPlus,
  Tag,
  History,
  Server,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import XaiGlyph from './XaiGlyph';

export const ICONS = {
  // ---- room / navigation icons (core/rooms.ts) ----
  observatory: Orbit,
  neuralCore: Brain,
  neuralCapture: MessageCircleQuestion,
  projects: FolderKanban,
  focusTime: Target,
  designStudio: Palette,
  roadmaps: Map,
  bugTracker: Bug,
  releases: Package,
  memoryVault: Archive,
  comms: Satellite,
  settings: Settings,
  browser: Globe,
  knowledgeMatrix: Network,
  terminal: SquareTerminal,

  // ---- generic content / entity icons ----
  file: FileText,
  link: Link2,
  image: Image,
  message: MessageSquare,
  puzzle: Puzzle,
  bone: Bone,
  brush: Paintbrush,
  pen: PenLine,
  pin: Pin,
  mic: Mic,
  music: Music,
  globe: Globe,
  checkCircle: CheckCircle2,
  note: NotebookPen,
  idea: Lightbulb,
  clapper: Clapperboard,
  chart: BarChart3,
  wind: Wind,
  eraser: Eraser,
  bucket: PaintBucket,
  droplet: Droplet,
  rain: CloudRain,
  headphones: Headphones,
  smile: Smile,
  meh: Meh,
  frown: Frown,
  laptop: Laptop,
  sprout: Sprout,
  telescope: Telescope,
  camera: Camera,
  hand: Hand,
  mute: VolumeX,

  // ---- directional / chrome ----
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowUpDown: ArrowUpDown,
  arrowUpRight: ArrowUpRight,
  swap: ArrowLeftRight,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  close: X,
  check: Check,
  diamond: Diamond,
  circle: Circle,
  square: Square,
  rect: RectangleHorizontal,
  star: Star,
  warning: AlertTriangle,
  play: Play,
  pause: Pause,
  save: Save,
  folderOpen: FolderOpen,
  skipBack: SkipBack,
  undo: RotateCcw,
  redo: RotateCw,
  sparkles: Sparkles,
  more: MoreHorizontal,
  menu: Menu,
  undo2: Undo2,
  redo2: Redo2,
  text: Type,
  scissors: Scissors,
  shuffle: Shuffle,
  command: Command,
  enter: CornerDownLeft,
  layers: Layers,
  grid: LayoutGrid,
  gridDense: Grid3x3,
  list: List,
  rows: Rows3,
  hexagon: Hexagon,
  diagram: Workflow,
  slidedeck: Presentation,
  wand: Wand2,
  stamp: Stamp,
  smudge: Blend,
  heal: Bandage,
  pencil: Pencil,
  select: MousePointer2,
  penTool: PenTool,
  hourglass: Hourglass,
  branch: GitBranch,
  bolt: Zap,
  plus: Plus,
  minus: Minus,
  search: Search,
  download: Download,
  upload: Upload,
  copy: Copy,
  trash: Trash2,
  refresh: RefreshCw,
  filter: Filter,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  bell: Bell,
  spinner: Loader2,
  externalLink: ExternalLink,
  user: User,
  book: BookOpen,
  send: Send,
  study: GraduationCap,
  nebula: Waves,
  mission: Flag,
  gantt: GanttChartSquare,
  stop: StopCircle,
  radial: Target,
  back: ArrowLeft,
  addToMatrix: BookmarkPlus,
  tag: Tag,
  history: History,
  server: Server,

  // ---- bespoke xOS brand glyph (not from lucide) ----
  xai: XaiGlyph,
} as const satisfies Record<string, LucideIcon | typeof XaiGlyph>;

export type IconName = keyof typeof ICONS;
